# PROMISE project source and metrics paths
projects:
  ant:
    sources:
      - PROMISE-backup-master/source-code/ant/ant-1.3
      - PROMISE-backup-master/source-code/ant/ant-1.4
      - PROMISE-backup-master/source-code/ant/ant-1.5
      - PROMISE-backup-master/source-code/ant/ant-1.6
      - PROMISE-backup-master/source-code/ant/ant-1.7
    metrics:
      - PROMISE-backup-master/bug-data/ant/ant-1.3.csv
      - PROMISE-backup-master/bug-data/ant/ant-1.4.csv
      - PROMISE-backup-master/bug-data/ant/ant-1.5.csv
      - PROMISE-backup-master/bug-data/ant/ant-1.6.csv
      - PROMISE-backup-master/bug-data/ant/ant-1.7.csv
  camel:
    sources:
      - PROMISE-backup-master/source-code/camel/camel-1.0
      - PROMISE-backup-master/source-code/camel/camel-1.2
      - PROMISE-backup-master/source-code/camel/camel-1.4
      - PROMISE-backup-master/source-code/camel/camel-1.6
    metrics:
      - PROMISE-backup-master/bug-data/camel/camel-1.0.csv
      - PROMISE-backup-master/bug-data/camel/camel-1.2.csv
      - PROMISE-backup-master/bug-data/camel/camel-1.4.csv
      - PROMISE-backup-master/bug-data/camel/camel-1.6.csv
  jedit:
    sources:
      - PROMISE-backup-master/source-code/jedit/jedit-3.2
      - PROMISE-backup-master/source-code/jedit/jedit-4.0
      - PROMISE-backup-master/source-code/jedit/jedit-4.1
      - PROMISE-backup-master/source-code/jedit/jedit-4.2
      - PROMISE-backup-master/source-code/jedit/jedit-4.3
    metrics:
      - PROMISE-backup-master/bug-data/jedit/jedit-3.2.csv
      - PROMISE-backup-master/bug-data/jedit/jedit-4.0.csv
      - PROMISE-backup-master/bug-data/jedit/jedit-4.1.csv
      - PROMISE-backup-master/bug-data/jedit/jedit-4.2.csv
      - PROMISE-backup-master/bug-data/jedit/jedit-4.3.csv
  log4j:
    sources:
      - PROMISE-backup-master/source-code/log4j/log4j-1.0
      - PROMISE-backup-master/source-code/log4j/log4j-1.1
      - PROMISE-backup-master/source-code/log4j/log4j-1.2
    metrics:
      - PROMISE-backup-master/bug-data/log4j/log4j-1.0.csv
      - PROMISE-backup-master/bug-data/log4j/log4j-1.1.csv
      - PROMISE-backup-master/bug-data/log4j/log4j-1.2.csv
  lucene:
    sources:
      - PROMISE-backup-master/source-code/lucene/lucene-2.0
      - PROMISE-backup-master/source-code/lucene/lucene-2.2
      - PROMISE-backup-master/source-code/lucene/lucene-2.4
    metrics:
      - PROMISE-backup-master/bug-data/lucene/lucene-2.0.csv
      - PROMISE-backup-master/bug-data/lucene/lucene-2.2.csv
      - PROMISE-backup-master/bug-data/lucene/lucene-2.4.csv
  poi:
    sources:
      - PROMISE-backup-master/source-code/poi/poi-1.5
      - PROMISE-backup-master/source-code/poi/poi-2.0
      - PROMISE-backup-master/source-code/poi/poi-2.5
      - PROMISE-backup-master/source-code/poi/poi-3.0
    metrics:
      - PROMISE-backup-master/bug-data/poi/poi-1.5.csv
      - PROMISE-backup-master/bug-data/poi/poi-2.0.csv
      - PROMISE-backup-master/bug-data/poi/poi-2.5.csv
      - PROMISE-backup-master/bug-data/poi/poi-3.0.csv
  synapse:
    sources:
      - PROMISE-backup-master/source-code/synapse/synapse-1.0
      - PROMISE-backup-master/source-code/synapse/synapse-1.1
      - PROMISE-backup-master/source-code/synapse/synapse-1.2
    metrics:
      - PROMISE-backup-master/bug-data/synapse/synapse-1.0.csv
      - PROMISE-backup-master/bug-data/synapse/synapse-1.1.csv
      - PROMISE-backup-master/bug-data/synapse/synapse-1.2.csv
  velocity:
    sources:
      - PROMISE-backup-master/source-code/velocity/velocity-1.4
      - PROMISE-backup-master/source-code/velocity/velocity-1.5
      - PROMISE-backup-master/source-code/velocity/velocity-1.6
    metrics:
      - PROMISE-backup-master/bug-data/velocity/velocity-1.4.csv
      - PROMISE-backup-master/bug-data/velocity/velocity-1.5.csv
      - PROMISE-backup-master/bug-data/velocity/velocity-1.6.csv
  xalan:
    sources:
      - PROMISE-backup-master/source-code/xalan/xalan-2.4
      - PROMISE-backup-master/source-code/xalan/xalan-2.5
      - PROMISE-backup-master/source-code/xalan/xalan-2.6
      - PROMISE-backup-master/source-code/xalan/xalan-2.7
    metrics:
      - PROMISE-backup-master/bug-data/xalan/xalan-2.4.csv
      - PROMISE-backup-master/bug-data/xalan/xalan-2.5.csv
      - PROMISE-backup-master/bug-data/xalan/xalan-2.6.csv
      - PROMISE-backup-master/bug-data/xalan/xalan-2.7.csv
  xerces:
    sources:
      - PROMISE-backup-master/source-code/xerces/xerces-1.1
      - PROMISE-backup-master/source-code/xerces/xerces-1.2
      - PROMISE-backup-master/source-code/xerces/xerces-1.3
      - PROMISE-backup-master/source-code/xerces/xerces-1.4.4
    metrics:
      - PROMISE-backup-master/bug-data/xerces/xerces-1.1.csv
      - PROMISE-backup-master/bug-data/xerces/xerces-1.2.csv
      - PROMISE-backup-master/bug-data/xerces/xerces-1.3.csv
      - PROMISE-backup-master/bug-data/xerces/xerces-1.4.4.csv